language: node_js

node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "4.1"

notifications:
  email:
    recipients:
      - martin@pipedrive.com
    on_success: change
    on_failure: change

script: "npm run-script test-travis"

after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"

sudo: false
